baseURL = "https://tradingrookie.com"
languageCode = "en-us"
title = "This rookie's Trading Blog"
theme = "PaperMod"

[params]
  author = "Raja Sleem"
  description = "A blog about trading."
  keywords = ["trading, stocks, finance"]
  defaultTheme = "auto"
  showBorder = true
  showBreadcrumbs = true
  showDateUpdated = true
  logo = "images/trading_rookie_logo.png"  # Make sure to place your logo in the static folder
  enableEmoji = true
  UseHugoToc = true
  DateFormat = "January 2, 2006"
  mainSections = ["blog"]

  [params.label]
    text = "This rookie's Trading Blog"
    icon = "/images/trading_rookie_logo.png"
    iconHeight = 45

  [menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "Posts Journey"
    name = "Posts Journey"
    url = "/posts-journey/"
    weight = 1


